name       : python-tinycss2
version    : 1.2.1
release    : 5
source     :
    - https://pypi.io/packages/source/t/tinycss2/tinycss2-1.2.1.tar.gz : 8cff3a8f066c2ec677c06dbc7b45619804a6938478d9d73c284b29d14ecb0627
homepage   : https://tinycss2.readthedocs.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Low-level CSS parser for Python
description: |
    tinycss2 is a low-level CSS parser and generator: it can parse strings, return Python objects representing tokens and blocks, and generate CSS strings corresponding to these objects.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - pytest-runner       # check
    - python-pytest-cov   # check
    - python-pytest-isort # check
    - python-webencodings
rundeps    :
    - python-webencodings
setup      : |
    sed -i 's/--flake8//' pyproject.toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
