name       : python-tinycss2
version    : 1.1.0
release    : 1
source     :
    - https://pypi.io/packages/source/t/tinycss2/tinycss2-1.1.0.tar.gz : fbdcac3044d60eb85fdb2aa840ece43cf7dbe798e373e6ee0be545d4d134e18a
    - git|https://github.com/SimonSapin/css-parsing-tests : c5749e51dda3868b3e8062e65a36584c2fec8059
homepage   : https://tinycss2.readthedocs.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Low-level CSS parser for Python
description: |
    tinycss2 is a low-level CSS parser and generator: it can parse strings, return Python objects representing tokens and blocks, and generate CSS strings corresponding to these objects.
builddeps  :
    - git
    - pytest-runner
    - python-pytest-cov
    - python-pytest-isort
    - python-webencodings
rundeps    :
    - python-webencodings
setup      : |
    sed -i 's/--flake8//' pyproject.toml
    cp $sources/css-parsing-tests.git/* tests/css-parsing-tests/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
