name       : python-tinycss2
version    : 1.1.1
release    : 4
source     :
    - https://pypi.io/packages/source/t/tinycss2/tinycss2-1.1.1.tar.gz : b2e44dd8883c360c35dd0d1b5aad0b610e5156c2cb3b33434634e539ead9d8bf
homepage   : https://tinycss2.readthedocs.io/
license    : BSD-3-Clause
component  : programming.python
summary    : Low-level CSS parser for Python
description: |
    tinycss2 is a low-level CSS parser and generator: it can parse strings, return Python objects representing tokens and blocks, and generate CSS strings corresponding to these objects.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - pytest-runner       # check
    - python-pytest-cov   # check
    - python-pytest-isort # check
    - python-webencodings
rundeps    :
    - python-webencodings
setup      : |
    sed -i 's/--flake8//' pyproject.toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
